import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Test kerbin griman',
  description: 'Generated by kerbin griman',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gradient-to-tl from-indigo-500 via-purple-500 to-pink-500 block h-screen items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  )
}
