import { Inter } from 'next/font/google'
import React from 'react'
import Header from '../../components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Test kerbin griman',
  description: 'Generated by kerbin griman',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <div className="bg-gradient-to-tl from-indigo-500 via-purple-500 to-pink-500 block h-screen items-center justify-center">
          <Header/>
          {children}
        </div>
  )
}
